id: PEB991369
initial_creation_type: ocr
source_metadata:
  volumes:
    4f7a836a2bd241e19fb4f0e698eccc85:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དེ་བཞིན་གཤེགས་པ་བདུན་གྱི་སྔོན་གྱི་སྨོན་ལམ་གྱི་ཁྱད་པར་རྒྱས་པའི་གཟུངས་བཀླག་པའི་ཆོ་ག་མདོ་སྡེ་ལས་བཏུས་པ།
      total_pages: 1044
      volume_number: 38
